
namespace PhBuy
{
    partial class SellerPanel
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SellerPanel));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.panel2 = new System.Windows.Forms.Panel();
            this.addProductButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.productButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel3 = new System.Windows.Forms.Panel();
            this.incomeButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ordersButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.analyticDropDown = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.orderDropDown = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.productDropDown = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.storeDropDown = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.chatButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.addProductButton);
            this.panel2.Controls.Add(this.productButton);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 74);
            this.panel2.Margin = new System.Windows.Forms.Padding(2);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(117, 66);
            this.panel2.TabIndex = 6;
            // 
            // addProductButton
            // 
            this.addProductButton.AllowAnimations = true;
            this.addProductButton.AllowMouseEffects = true;
            this.addProductButton.AllowToggling = false;
            this.addProductButton.AnimationSpeed = 200;
            this.addProductButton.AutoGenerateColors = false;
            this.addProductButton.AutoRoundBorders = false;
            this.addProductButton.AutoSizeLeftIcon = true;
            this.addProductButton.AutoSizeRightIcon = true;
            this.addProductButton.BackColor = System.Drawing.Color.Transparent;
            this.addProductButton.BackColor1 = System.Drawing.Color.White;
            this.addProductButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addProductButton.BackgroundImage")));
            this.addProductButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProductButton.ButtonText = "Add Product";
            this.addProductButton.ButtonTextMarginLeft = 0;
            this.addProductButton.ColorContrastOnClick = 45;
            this.addProductButton.ColorContrastOnHover = 45;
            this.addProductButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.addProductButton.CustomizableEdges = borderEdges6;
            this.addProductButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addProductButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addProductButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addProductButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addProductButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.addProductButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addProductButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addProductButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.addProductButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addProductButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addProductButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addProductButton.IconMarginLeft = 11;
            this.addProductButton.IconPadding = 10;
            this.addProductButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addProductButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addProductButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addProductButton.IconSize = 25;
            this.addProductButton.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.addProductButton.IdleBorderRadius = 1;
            this.addProductButton.IdleBorderThickness = 1;
            this.addProductButton.IdleFillColor = System.Drawing.Color.White;
            this.addProductButton.IdleIconLeftImage = null;
            this.addProductButton.IdleIconRightImage = null;
            this.addProductButton.IndicateFocus = false;
            this.addProductButton.Location = new System.Drawing.Point(0, 32);
            this.addProductButton.Margin = new System.Windows.Forms.Padding(2);
            this.addProductButton.Name = "addProductButton";
            this.addProductButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addProductButton.OnDisabledState.BorderRadius = 1;
            this.addProductButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProductButton.OnDisabledState.BorderThickness = 1;
            this.addProductButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addProductButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addProductButton.OnDisabledState.IconLeftImage = null;
            this.addProductButton.OnDisabledState.IconRightImage = null;
            this.addProductButton.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.addProductButton.onHoverState.BorderRadius = 1;
            this.addProductButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProductButton.onHoverState.BorderThickness = 1;
            this.addProductButton.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.addProductButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.addProductButton.onHoverState.IconLeftImage = null;
            this.addProductButton.onHoverState.IconRightImage = null;
            this.addProductButton.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.addProductButton.OnIdleState.BorderRadius = 1;
            this.addProductButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProductButton.OnIdleState.BorderThickness = 1;
            this.addProductButton.OnIdleState.FillColor = System.Drawing.Color.White;
            this.addProductButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.addProductButton.OnIdleState.IconLeftImage = null;
            this.addProductButton.OnIdleState.IconRightImage = null;
            this.addProductButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.addProductButton.OnPressedState.BorderRadius = 1;
            this.addProductButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addProductButton.OnPressedState.BorderThickness = 1;
            this.addProductButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.addProductButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addProductButton.OnPressedState.IconLeftImage = null;
            this.addProductButton.OnPressedState.IconRightImage = null;
            this.addProductButton.Size = new System.Drawing.Size(117, 32);
            this.addProductButton.TabIndex = 1;
            this.addProductButton.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addProductButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addProductButton.TextMarginLeft = 0;
            this.addProductButton.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.addProductButton.UseDefaultRadiusAndThickness = true;
            this.addProductButton.Click += new System.EventHandler(this.addProductButton_Click);
            // 
            // productButton
            // 
            this.productButton.AllowAnimations = true;
            this.productButton.AllowMouseEffects = true;
            this.productButton.AllowToggling = false;
            this.productButton.AnimationSpeed = 200;
            this.productButton.AutoGenerateColors = false;
            this.productButton.AutoRoundBorders = false;
            this.productButton.AutoSizeLeftIcon = true;
            this.productButton.AutoSizeRightIcon = true;
            this.productButton.BackColor = System.Drawing.Color.Transparent;
            this.productButton.BackColor1 = System.Drawing.Color.White;
            this.productButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productButton.BackgroundImage")));
            this.productButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productButton.ButtonText = "My Products";
            this.productButton.ButtonTextMarginLeft = 0;
            this.productButton.ColorContrastOnClick = 45;
            this.productButton.ColorContrastOnHover = 45;
            this.productButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.productButton.CustomizableEdges = borderEdges7;
            this.productButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.productButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.productButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.productButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.productButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.productButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.productButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.productButton.IconMarginLeft = 11;
            this.productButton.IconPadding = 10;
            this.productButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.productButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.productButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.productButton.IconSize = 25;
            this.productButton.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.productButton.IdleBorderRadius = 1;
            this.productButton.IdleBorderThickness = 1;
            this.productButton.IdleFillColor = System.Drawing.Color.White;
            this.productButton.IdleIconLeftImage = null;
            this.productButton.IdleIconRightImage = null;
            this.productButton.IndicateFocus = false;
            this.productButton.Location = new System.Drawing.Point(0, 0);
            this.productButton.Margin = new System.Windows.Forms.Padding(2);
            this.productButton.Name = "productButton";
            this.productButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productButton.OnDisabledState.BorderRadius = 1;
            this.productButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productButton.OnDisabledState.BorderThickness = 1;
            this.productButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productButton.OnDisabledState.IconLeftImage = null;
            this.productButton.OnDisabledState.IconRightImage = null;
            this.productButton.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.productButton.onHoverState.BorderRadius = 1;
            this.productButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productButton.onHoverState.BorderThickness = 1;
            this.productButton.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.productButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.productButton.onHoverState.IconLeftImage = null;
            this.productButton.onHoverState.IconRightImage = null;
            this.productButton.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.productButton.OnIdleState.BorderRadius = 1;
            this.productButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productButton.OnIdleState.BorderThickness = 1;
            this.productButton.OnIdleState.FillColor = System.Drawing.Color.White;
            this.productButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.productButton.OnIdleState.IconLeftImage = null;
            this.productButton.OnIdleState.IconRightImage = null;
            this.productButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.productButton.OnPressedState.BorderRadius = 1;
            this.productButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productButton.OnPressedState.BorderThickness = 1;
            this.productButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.productButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.productButton.OnPressedState.IconLeftImage = null;
            this.productButton.OnPressedState.IconRightImage = null;
            this.productButton.Size = new System.Drawing.Size(117, 32);
            this.productButton.TabIndex = 0;
            this.productButton.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.productButton.TextMarginLeft = 0;
            this.productButton.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.productButton.UseDefaultRadiusAndThickness = true;
            this.productButton.Click += new System.EventHandler(this.productButton_Click);
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.incomeButton);
            this.panel3.Controls.Add(this.ordersButton);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel3.Location = new System.Drawing.Point(0, 177);
            this.panel3.Margin = new System.Windows.Forms.Padding(2);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(117, 66);
            this.panel3.TabIndex = 8;
            // 
            // incomeButton
            // 
            this.incomeButton.AllowAnimations = true;
            this.incomeButton.AllowMouseEffects = true;
            this.incomeButton.AllowToggling = false;
            this.incomeButton.AnimationSpeed = 200;
            this.incomeButton.AutoGenerateColors = false;
            this.incomeButton.AutoRoundBorders = false;
            this.incomeButton.AutoSizeLeftIcon = true;
            this.incomeButton.AutoSizeRightIcon = true;
            this.incomeButton.BackColor = System.Drawing.Color.Transparent;
            this.incomeButton.BackColor1 = System.Drawing.Color.White;
            this.incomeButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("incomeButton.BackgroundImage")));
            this.incomeButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.incomeButton.ButtonText = "My Income";
            this.incomeButton.ButtonTextMarginLeft = 0;
            this.incomeButton.ColorContrastOnClick = 45;
            this.incomeButton.ColorContrastOnHover = 45;
            this.incomeButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.incomeButton.CustomizableEdges = borderEdges3;
            this.incomeButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.incomeButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.incomeButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.incomeButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.incomeButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.incomeButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.incomeButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.incomeButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.incomeButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.incomeButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.incomeButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.incomeButton.IconMarginLeft = 11;
            this.incomeButton.IconPadding = 10;
            this.incomeButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.incomeButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.incomeButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.incomeButton.IconSize = 25;
            this.incomeButton.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.incomeButton.IdleBorderRadius = 1;
            this.incomeButton.IdleBorderThickness = 1;
            this.incomeButton.IdleFillColor = System.Drawing.Color.White;
            this.incomeButton.IdleIconLeftImage = null;
            this.incomeButton.IdleIconRightImage = null;
            this.incomeButton.IndicateFocus = false;
            this.incomeButton.Location = new System.Drawing.Point(0, 32);
            this.incomeButton.Margin = new System.Windows.Forms.Padding(2);
            this.incomeButton.Name = "incomeButton";
            this.incomeButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.incomeButton.OnDisabledState.BorderRadius = 1;
            this.incomeButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.incomeButton.OnDisabledState.BorderThickness = 1;
            this.incomeButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.incomeButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.incomeButton.OnDisabledState.IconLeftImage = null;
            this.incomeButton.OnDisabledState.IconRightImage = null;
            this.incomeButton.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.incomeButton.onHoverState.BorderRadius = 1;
            this.incomeButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.incomeButton.onHoverState.BorderThickness = 1;
            this.incomeButton.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.incomeButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.incomeButton.onHoverState.IconLeftImage = null;
            this.incomeButton.onHoverState.IconRightImage = null;
            this.incomeButton.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.incomeButton.OnIdleState.BorderRadius = 1;
            this.incomeButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.incomeButton.OnIdleState.BorderThickness = 1;
            this.incomeButton.OnIdleState.FillColor = System.Drawing.Color.White;
            this.incomeButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.incomeButton.OnIdleState.IconLeftImage = null;
            this.incomeButton.OnIdleState.IconRightImage = null;
            this.incomeButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.incomeButton.OnPressedState.BorderRadius = 1;
            this.incomeButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.incomeButton.OnPressedState.BorderThickness = 1;
            this.incomeButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.incomeButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.incomeButton.OnPressedState.IconLeftImage = null;
            this.incomeButton.OnPressedState.IconRightImage = null;
            this.incomeButton.Size = new System.Drawing.Size(117, 32);
            this.incomeButton.TabIndex = 0;
            this.incomeButton.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.incomeButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.incomeButton.TextMarginLeft = 0;
            this.incomeButton.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.incomeButton.UseDefaultRadiusAndThickness = true;
            this.incomeButton.Click += new System.EventHandler(this.incomeButton_Click);
            // 
            // ordersButton
            // 
            this.ordersButton.AllowAnimations = true;
            this.ordersButton.AllowMouseEffects = true;
            this.ordersButton.AllowToggling = false;
            this.ordersButton.AnimationSpeed = 200;
            this.ordersButton.AutoGenerateColors = false;
            this.ordersButton.AutoRoundBorders = false;
            this.ordersButton.AutoSizeLeftIcon = true;
            this.ordersButton.AutoSizeRightIcon = true;
            this.ordersButton.BackColor = System.Drawing.Color.Transparent;
            this.ordersButton.BackColor1 = System.Drawing.Color.White;
            this.ordersButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ordersButton.BackgroundImage")));
            this.ordersButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersButton.ButtonText = "My Orders";
            this.ordersButton.ButtonTextMarginLeft = 0;
            this.ordersButton.ColorContrastOnClick = 45;
            this.ordersButton.ColorContrastOnHover = 45;
            this.ordersButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.ordersButton.CustomizableEdges = borderEdges4;
            this.ordersButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ordersButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ordersButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ordersButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ordersButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.ordersButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ordersButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ordersButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.ordersButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ordersButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ordersButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ordersButton.IconMarginLeft = 11;
            this.ordersButton.IconPadding = 10;
            this.ordersButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ordersButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ordersButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ordersButton.IconSize = 25;
            this.ordersButton.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.ordersButton.IdleBorderRadius = 1;
            this.ordersButton.IdleBorderThickness = 1;
            this.ordersButton.IdleFillColor = System.Drawing.Color.White;
            this.ordersButton.IdleIconLeftImage = null;
            this.ordersButton.IdleIconRightImage = null;
            this.ordersButton.IndicateFocus = false;
            this.ordersButton.Location = new System.Drawing.Point(0, 0);
            this.ordersButton.Margin = new System.Windows.Forms.Padding(2);
            this.ordersButton.Name = "ordersButton";
            this.ordersButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ordersButton.OnDisabledState.BorderRadius = 1;
            this.ordersButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersButton.OnDisabledState.BorderThickness = 1;
            this.ordersButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ordersButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ordersButton.OnDisabledState.IconLeftImage = null;
            this.ordersButton.OnDisabledState.IconRightImage = null;
            this.ordersButton.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.ordersButton.onHoverState.BorderRadius = 1;
            this.ordersButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersButton.onHoverState.BorderThickness = 1;
            this.ordersButton.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.ordersButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.ordersButton.onHoverState.IconLeftImage = null;
            this.ordersButton.onHoverState.IconRightImage = null;
            this.ordersButton.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.ordersButton.OnIdleState.BorderRadius = 1;
            this.ordersButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersButton.OnIdleState.BorderThickness = 1;
            this.ordersButton.OnIdleState.FillColor = System.Drawing.Color.White;
            this.ordersButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.ordersButton.OnIdleState.IconLeftImage = null;
            this.ordersButton.OnIdleState.IconRightImage = null;
            this.ordersButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.ordersButton.OnPressedState.BorderRadius = 1;
            this.ordersButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ordersButton.OnPressedState.BorderThickness = 1;
            this.ordersButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(182)))), ((int)(((byte)(64)))));
            this.ordersButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ordersButton.OnPressedState.IconLeftImage = null;
            this.ordersButton.OnPressedState.IconRightImage = null;
            this.ordersButton.Size = new System.Drawing.Size(117, 32);
            this.ordersButton.TabIndex = 0;
            this.ordersButton.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ordersButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ordersButton.TextMarginLeft = 0;
            this.ordersButton.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.ordersButton.UseDefaultRadiusAndThickness = true;
            this.ordersButton.Click += new System.EventHandler(this.ordersButton_Click);
            // 
            // analyticDropDown
            // 
            this.analyticDropDown.AllowAnimations = true;
            this.analyticDropDown.AllowMouseEffects = true;
            this.analyticDropDown.AllowToggling = false;
            this.analyticDropDown.AnimationSpeed = 200;
            this.analyticDropDown.AutoGenerateColors = false;
            this.analyticDropDown.AutoRoundBorders = false;
            this.analyticDropDown.AutoSizeLeftIcon = true;
            this.analyticDropDown.AutoSizeRightIcon = true;
            this.analyticDropDown.BackColor = System.Drawing.Color.Transparent;
            this.analyticDropDown.BackColor1 = System.Drawing.Color.White;
            this.analyticDropDown.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("analyticDropDown.BackgroundImage")));
            this.analyticDropDown.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.analyticDropDown.ButtonText = "Analytics";
            this.analyticDropDown.ButtonTextMarginLeft = 0;
            this.analyticDropDown.ColorContrastOnClick = 45;
            this.analyticDropDown.ColorContrastOnHover = 45;
            this.analyticDropDown.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.analyticDropDown.CustomizableEdges = borderEdges2;
            this.analyticDropDown.DialogResult = System.Windows.Forms.DialogResult.None;
            this.analyticDropDown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.analyticDropDown.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.analyticDropDown.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.analyticDropDown.Dock = System.Windows.Forms.DockStyle.Top;
            this.analyticDropDown.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.analyticDropDown.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.analyticDropDown.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.analyticDropDown.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.analyticDropDown.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.analyticDropDown.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.analyticDropDown.IconMarginLeft = 11;
            this.analyticDropDown.IconPadding = 10;
            this.analyticDropDown.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.analyticDropDown.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.analyticDropDown.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.analyticDropDown.IconSize = 25;
            this.analyticDropDown.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.analyticDropDown.IdleBorderRadius = 1;
            this.analyticDropDown.IdleBorderThickness = 1;
            this.analyticDropDown.IdleFillColor = System.Drawing.Color.White;
            this.analyticDropDown.IdleIconLeftImage = global::PhBuy.Properties.Resources.graph_500px;
            this.analyticDropDown.IdleIconRightImage = null;
            this.analyticDropDown.IndicateFocus = false;
            this.analyticDropDown.Location = new System.Drawing.Point(0, 243);
            this.analyticDropDown.Margin = new System.Windows.Forms.Padding(2);
            this.analyticDropDown.Name = "analyticDropDown";
            this.analyticDropDown.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.analyticDropDown.OnDisabledState.BorderRadius = 1;
            this.analyticDropDown.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.analyticDropDown.OnDisabledState.BorderThickness = 1;
            this.analyticDropDown.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.analyticDropDown.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.analyticDropDown.OnDisabledState.IconLeftImage = null;
            this.analyticDropDown.OnDisabledState.IconRightImage = null;
            this.analyticDropDown.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.analyticDropDown.onHoverState.BorderRadius = 1;
            this.analyticDropDown.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.analyticDropDown.onHoverState.BorderThickness = 1;
            this.analyticDropDown.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.analyticDropDown.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.analyticDropDown.onHoverState.IconLeftImage = null;
            this.analyticDropDown.onHoverState.IconRightImage = null;
            this.analyticDropDown.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.analyticDropDown.OnIdleState.BorderRadius = 1;
            this.analyticDropDown.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.analyticDropDown.OnIdleState.BorderThickness = 1;
            this.analyticDropDown.OnIdleState.FillColor = System.Drawing.Color.White;
            this.analyticDropDown.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.analyticDropDown.OnIdleState.IconLeftImage = global::PhBuy.Properties.Resources.graph_500px;
            this.analyticDropDown.OnIdleState.IconRightImage = null;
            this.analyticDropDown.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.analyticDropDown.OnPressedState.BorderRadius = 1;
            this.analyticDropDown.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.analyticDropDown.OnPressedState.BorderThickness = 1;
            this.analyticDropDown.OnPressedState.FillColor = System.Drawing.Color.White;
            this.analyticDropDown.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.analyticDropDown.OnPressedState.IconLeftImage = null;
            this.analyticDropDown.OnPressedState.IconRightImage = null;
            this.analyticDropDown.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.analyticDropDown.Size = new System.Drawing.Size(117, 37);
            this.analyticDropDown.TabIndex = 9;
            this.analyticDropDown.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.analyticDropDown.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.analyticDropDown.TextMarginLeft = 0;
            this.analyticDropDown.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.analyticDropDown.UseDefaultRadiusAndThickness = true;
            this.analyticDropDown.Click += new System.EventHandler(this.insightButton_Click);
            // 
            // orderDropDown
            // 
            this.orderDropDown.AllowAnimations = true;
            this.orderDropDown.AllowMouseEffects = true;
            this.orderDropDown.AllowToggling = false;
            this.orderDropDown.AnimationSpeed = 200;
            this.orderDropDown.AutoGenerateColors = false;
            this.orderDropDown.AutoRoundBorders = false;
            this.orderDropDown.AutoSizeLeftIcon = true;
            this.orderDropDown.AutoSizeRightIcon = true;
            this.orderDropDown.BackColor = System.Drawing.Color.Transparent;
            this.orderDropDown.BackColor1 = System.Drawing.Color.White;
            this.orderDropDown.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("orderDropDown.BackgroundImage")));
            this.orderDropDown.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderDropDown.ButtonText = "Orders";
            this.orderDropDown.ButtonTextMarginLeft = 0;
            this.orderDropDown.ColorContrastOnClick = 45;
            this.orderDropDown.ColorContrastOnHover = 45;
            this.orderDropDown.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.orderDropDown.CustomizableEdges = borderEdges5;
            this.orderDropDown.DialogResult = System.Windows.Forms.DialogResult.None;
            this.orderDropDown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.orderDropDown.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.orderDropDown.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.orderDropDown.Dock = System.Windows.Forms.DockStyle.Top;
            this.orderDropDown.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.orderDropDown.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.orderDropDown.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.orderDropDown.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.orderDropDown.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.orderDropDown.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.orderDropDown.IconMarginLeft = 11;
            this.orderDropDown.IconPadding = 10;
            this.orderDropDown.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.orderDropDown.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.orderDropDown.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.orderDropDown.IconSize = 25;
            this.orderDropDown.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.orderDropDown.IdleBorderRadius = 1;
            this.orderDropDown.IdleBorderThickness = 1;
            this.orderDropDown.IdleFillColor = System.Drawing.Color.White;
            this.orderDropDown.IdleIconLeftImage = global::PhBuy.Properties.Resources.shopping_bag_500px;
            this.orderDropDown.IdleIconRightImage = null;
            this.orderDropDown.IndicateFocus = false;
            this.orderDropDown.Location = new System.Drawing.Point(0, 140);
            this.orderDropDown.Margin = new System.Windows.Forms.Padding(2);
            this.orderDropDown.Name = "orderDropDown";
            this.orderDropDown.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.orderDropDown.OnDisabledState.BorderRadius = 1;
            this.orderDropDown.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderDropDown.OnDisabledState.BorderThickness = 1;
            this.orderDropDown.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.orderDropDown.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.orderDropDown.OnDisabledState.IconLeftImage = null;
            this.orderDropDown.OnDisabledState.IconRightImage = null;
            this.orderDropDown.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.orderDropDown.onHoverState.BorderRadius = 1;
            this.orderDropDown.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderDropDown.onHoverState.BorderThickness = 1;
            this.orderDropDown.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.orderDropDown.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.orderDropDown.onHoverState.IconLeftImage = null;
            this.orderDropDown.onHoverState.IconRightImage = null;
            this.orderDropDown.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.orderDropDown.OnIdleState.BorderRadius = 1;
            this.orderDropDown.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderDropDown.OnIdleState.BorderThickness = 1;
            this.orderDropDown.OnIdleState.FillColor = System.Drawing.Color.White;
            this.orderDropDown.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.orderDropDown.OnIdleState.IconLeftImage = global::PhBuy.Properties.Resources.shopping_bag_500px;
            this.orderDropDown.OnIdleState.IconRightImage = null;
            this.orderDropDown.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.orderDropDown.OnPressedState.BorderRadius = 1;
            this.orderDropDown.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.orderDropDown.OnPressedState.BorderThickness = 1;
            this.orderDropDown.OnPressedState.FillColor = System.Drawing.Color.White;
            this.orderDropDown.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.orderDropDown.OnPressedState.IconLeftImage = null;
            this.orderDropDown.OnPressedState.IconRightImage = null;
            this.orderDropDown.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.orderDropDown.Size = new System.Drawing.Size(117, 37);
            this.orderDropDown.TabIndex = 7;
            this.orderDropDown.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.orderDropDown.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.orderDropDown.TextMarginLeft = 0;
            this.orderDropDown.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.orderDropDown.UseDefaultRadiusAndThickness = true;
            this.orderDropDown.Click += new System.EventHandler(this.dropDown_Click);
            // 
            // productDropDown
            // 
            this.productDropDown.AllowAnimations = true;
            this.productDropDown.AllowMouseEffects = true;
            this.productDropDown.AllowToggling = false;
            this.productDropDown.AnimationSpeed = 200;
            this.productDropDown.AutoGenerateColors = false;
            this.productDropDown.AutoRoundBorders = false;
            this.productDropDown.AutoSizeLeftIcon = true;
            this.productDropDown.AutoSizeRightIcon = true;
            this.productDropDown.BackColor = System.Drawing.Color.Transparent;
            this.productDropDown.BackColor1 = System.Drawing.Color.White;
            this.productDropDown.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productDropDown.BackgroundImage")));
            this.productDropDown.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productDropDown.ButtonText = "Products";
            this.productDropDown.ButtonTextMarginLeft = 0;
            this.productDropDown.ColorContrastOnClick = 45;
            this.productDropDown.ColorContrastOnHover = 45;
            this.productDropDown.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.productDropDown.CustomizableEdges = borderEdges8;
            this.productDropDown.DialogResult = System.Windows.Forms.DialogResult.None;
            this.productDropDown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productDropDown.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productDropDown.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productDropDown.Dock = System.Windows.Forms.DockStyle.Top;
            this.productDropDown.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.productDropDown.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.productDropDown.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.productDropDown.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productDropDown.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.productDropDown.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.productDropDown.IconMarginLeft = 11;
            this.productDropDown.IconPadding = 10;
            this.productDropDown.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.productDropDown.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.productDropDown.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.productDropDown.IconSize = 25;
            this.productDropDown.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.productDropDown.IdleBorderRadius = 1;
            this.productDropDown.IdleBorderThickness = 1;
            this.productDropDown.IdleFillColor = System.Drawing.Color.White;
            this.productDropDown.IdleIconLeftImage = global::PhBuy.Properties.Resources.product_documents_512px;
            this.productDropDown.IdleIconRightImage = null;
            this.productDropDown.IndicateFocus = false;
            this.productDropDown.Location = new System.Drawing.Point(0, 37);
            this.productDropDown.Margin = new System.Windows.Forms.Padding(2);
            this.productDropDown.Name = "productDropDown";
            this.productDropDown.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.productDropDown.OnDisabledState.BorderRadius = 1;
            this.productDropDown.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productDropDown.OnDisabledState.BorderThickness = 1;
            this.productDropDown.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productDropDown.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.productDropDown.OnDisabledState.IconLeftImage = null;
            this.productDropDown.OnDisabledState.IconRightImage = null;
            this.productDropDown.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.productDropDown.onHoverState.BorderRadius = 1;
            this.productDropDown.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productDropDown.onHoverState.BorderThickness = 1;
            this.productDropDown.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.productDropDown.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.productDropDown.onHoverState.IconLeftImage = null;
            this.productDropDown.onHoverState.IconRightImage = null;
            this.productDropDown.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.productDropDown.OnIdleState.BorderRadius = 1;
            this.productDropDown.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productDropDown.OnIdleState.BorderThickness = 1;
            this.productDropDown.OnIdleState.FillColor = System.Drawing.Color.White;
            this.productDropDown.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.productDropDown.OnIdleState.IconLeftImage = global::PhBuy.Properties.Resources.product_documents_512px;
            this.productDropDown.OnIdleState.IconRightImage = null;
            this.productDropDown.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.productDropDown.OnPressedState.BorderRadius = 1;
            this.productDropDown.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.productDropDown.OnPressedState.BorderThickness = 1;
            this.productDropDown.OnPressedState.FillColor = System.Drawing.Color.White;
            this.productDropDown.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.productDropDown.OnPressedState.IconLeftImage = null;
            this.productDropDown.OnPressedState.IconRightImage = null;
            this.productDropDown.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.productDropDown.Size = new System.Drawing.Size(117, 37);
            this.productDropDown.TabIndex = 5;
            this.productDropDown.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.productDropDown.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.productDropDown.TextMarginLeft = 0;
            this.productDropDown.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.productDropDown.UseDefaultRadiusAndThickness = true;
            this.productDropDown.Click += new System.EventHandler(this.dropDown_Click);
            // 
            // storeDropDown
            // 
            this.storeDropDown.AllowAnimations = true;
            this.storeDropDown.AllowMouseEffects = true;
            this.storeDropDown.AllowToggling = false;
            this.storeDropDown.AnimationSpeed = 200;
            this.storeDropDown.AutoGenerateColors = false;
            this.storeDropDown.AutoRoundBorders = false;
            this.storeDropDown.AutoSizeLeftIcon = true;
            this.storeDropDown.AutoSizeRightIcon = true;
            this.storeDropDown.BackColor = System.Drawing.Color.Transparent;
            this.storeDropDown.BackColor1 = System.Drawing.Color.White;
            this.storeDropDown.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("storeDropDown.BackgroundImage")));
            this.storeDropDown.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storeDropDown.ButtonText = "Store";
            this.storeDropDown.ButtonTextMarginLeft = 0;
            this.storeDropDown.ColorContrastOnClick = 45;
            this.storeDropDown.ColorContrastOnHover = 45;
            this.storeDropDown.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.storeDropDown.CustomizableEdges = borderEdges9;
            this.storeDropDown.DialogResult = System.Windows.Forms.DialogResult.None;
            this.storeDropDown.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.storeDropDown.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(58)))), ((int)(((byte)(39)))));
            this.storeDropDown.DisabledForecolor = System.Drawing.Color.White;
            this.storeDropDown.Dock = System.Windows.Forms.DockStyle.Top;
            this.storeDropDown.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.storeDropDown.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.storeDropDown.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.storeDropDown.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.storeDropDown.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.storeDropDown.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.storeDropDown.IconMarginLeft = 11;
            this.storeDropDown.IconPadding = 10;
            this.storeDropDown.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.storeDropDown.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.storeDropDown.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.storeDropDown.IconSize = 25;
            this.storeDropDown.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.storeDropDown.IdleBorderRadius = 1;
            this.storeDropDown.IdleBorderThickness = 1;
            this.storeDropDown.IdleFillColor = System.Drawing.Color.White;
            this.storeDropDown.IdleIconLeftImage = global::PhBuy.Properties.Resources.online_store_512px;
            this.storeDropDown.IdleIconRightImage = null;
            this.storeDropDown.IndicateFocus = false;
            this.storeDropDown.Location = new System.Drawing.Point(0, 0);
            this.storeDropDown.Margin = new System.Windows.Forms.Padding(2);
            this.storeDropDown.Name = "storeDropDown";
            this.storeDropDown.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.storeDropDown.OnDisabledState.BorderRadius = 1;
            this.storeDropDown.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storeDropDown.OnDisabledState.BorderThickness = 1;
            this.storeDropDown.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(58)))), ((int)(((byte)(39)))));
            this.storeDropDown.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.storeDropDown.OnDisabledState.IconLeftImage = null;
            this.storeDropDown.OnDisabledState.IconRightImage = null;
            this.storeDropDown.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.storeDropDown.onHoverState.BorderRadius = 1;
            this.storeDropDown.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storeDropDown.onHoverState.BorderThickness = 1;
            this.storeDropDown.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.storeDropDown.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.storeDropDown.onHoverState.IconLeftImage = null;
            this.storeDropDown.onHoverState.IconRightImage = null;
            this.storeDropDown.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.storeDropDown.OnIdleState.BorderRadius = 1;
            this.storeDropDown.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storeDropDown.OnIdleState.BorderThickness = 1;
            this.storeDropDown.OnIdleState.FillColor = System.Drawing.Color.White;
            this.storeDropDown.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.storeDropDown.OnIdleState.IconLeftImage = global::PhBuy.Properties.Resources.online_store_512px;
            this.storeDropDown.OnIdleState.IconRightImage = null;
            this.storeDropDown.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.storeDropDown.OnPressedState.BorderRadius = 1;
            this.storeDropDown.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.storeDropDown.OnPressedState.BorderThickness = 1;
            this.storeDropDown.OnPressedState.FillColor = System.Drawing.Color.White;
            this.storeDropDown.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.storeDropDown.OnPressedState.IconLeftImage = null;
            this.storeDropDown.OnPressedState.IconRightImage = null;
            this.storeDropDown.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.storeDropDown.Size = new System.Drawing.Size(117, 37);
            this.storeDropDown.TabIndex = 3;
            this.storeDropDown.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.storeDropDown.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.storeDropDown.TextMarginLeft = 0;
            this.storeDropDown.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.storeDropDown.UseDefaultRadiusAndThickness = true;
            this.storeDropDown.Click += new System.EventHandler(this.profileButton_Click);
            // 
            // chatButton
            // 
            this.chatButton.AllowAnimations = true;
            this.chatButton.AllowMouseEffects = true;
            this.chatButton.AllowToggling = false;
            this.chatButton.AnimationSpeed = 200;
            this.chatButton.AutoGenerateColors = false;
            this.chatButton.AutoRoundBorders = false;
            this.chatButton.AutoSizeLeftIcon = true;
            this.chatButton.AutoSizeRightIcon = true;
            this.chatButton.BackColor = System.Drawing.Color.Transparent;
            this.chatButton.BackColor1 = System.Drawing.Color.White;
            this.chatButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("chatButton.BackgroundImage")));
            this.chatButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chatButton.ButtonText = "Chat";
            this.chatButton.ButtonTextMarginLeft = 0;
            this.chatButton.ColorContrastOnClick = 45;
            this.chatButton.ColorContrastOnHover = 45;
            this.chatButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.chatButton.CustomizableEdges = borderEdges1;
            this.chatButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.chatButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.chatButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.chatButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.chatButton.Dock = System.Windows.Forms.DockStyle.Top;
            this.chatButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.chatButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Bold);
            this.chatButton.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.chatButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.chatButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.chatButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.chatButton.IconMarginLeft = 11;
            this.chatButton.IconPadding = 10;
            this.chatButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chatButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.chatButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.chatButton.IconSize = 25;
            this.chatButton.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.chatButton.IdleBorderRadius = 1;
            this.chatButton.IdleBorderThickness = 1;
            this.chatButton.IdleFillColor = System.Drawing.Color.White;
            this.chatButton.IdleIconLeftImage = global::PhBuy.Properties.Resources.chat_208px;
            this.chatButton.IdleIconRightImage = null;
            this.chatButton.IndicateFocus = false;
            this.chatButton.Location = new System.Drawing.Point(0, 280);
            this.chatButton.Margin = new System.Windows.Forms.Padding(2);
            this.chatButton.Name = "chatButton";
            this.chatButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.chatButton.OnDisabledState.BorderRadius = 1;
            this.chatButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chatButton.OnDisabledState.BorderThickness = 1;
            this.chatButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.chatButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.chatButton.OnDisabledState.IconLeftImage = null;
            this.chatButton.OnDisabledState.IconRightImage = null;
            this.chatButton.onHoverState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.chatButton.onHoverState.BorderRadius = 1;
            this.chatButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chatButton.onHoverState.BorderThickness = 1;
            this.chatButton.onHoverState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.chatButton.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.chatButton.onHoverState.IconLeftImage = null;
            this.chatButton.onHoverState.IconRightImage = null;
            this.chatButton.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.chatButton.OnIdleState.BorderRadius = 1;
            this.chatButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chatButton.OnIdleState.BorderThickness = 1;
            this.chatButton.OnIdleState.FillColor = System.Drawing.Color.White;
            this.chatButton.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(123)))), ((int)(((byte)(124)))), ((int)(((byte)(134)))));
            this.chatButton.OnIdleState.IconLeftImage = global::PhBuy.Properties.Resources.chat_208px;
            this.chatButton.OnIdleState.IconRightImage = null;
            this.chatButton.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.chatButton.OnPressedState.BorderRadius = 1;
            this.chatButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.chatButton.OnPressedState.BorderThickness = 1;
            this.chatButton.OnPressedState.FillColor = System.Drawing.Color.White;
            this.chatButton.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(41)))), ((int)(((byte)(66)))));
            this.chatButton.OnPressedState.IconLeftImage = null;
            this.chatButton.OnPressedState.IconRightImage = null;
            this.chatButton.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.chatButton.Size = new System.Drawing.Size(117, 37);
            this.chatButton.TabIndex = 9;
            this.chatButton.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.chatButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.chatButton.TextMarginLeft = 0;
            this.chatButton.TextPadding = new System.Windows.Forms.Padding(30, 0, 0, 0);
            this.chatButton.UseDefaultRadiusAndThickness = true;
            this.chatButton.Click += new System.EventHandler(this.chatButton_Click);
            // 
            // SellerPanel
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(117, 509);
            this.Controls.Add(this.chatButton);
            this.Controls.Add(this.analyticDropDown);
            this.Controls.Add(this.panel3);
            this.Controls.Add(this.orderDropDown);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.productDropDown);
            this.Controls.Add(this.storeDropDown);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "SellerPanel";
            this.Text = "SellerPanel";
            this.Load += new System.EventHandler(this.SellerPanel_Load);
            this.panel2.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton storeDropDown;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addProductButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton productButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton productDropDown;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton analyticDropDown;
        private System.Windows.Forms.Panel panel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton incomeButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton orderDropDown;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ordersButton;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton chatButton;
    }
}